# Generated by Django 6.0.3 on 2026-07-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanilies', '0031_cakeorder_stock_deducted_package_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakeorder',
            name='customer_archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packageorder',
            name='customer_archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
